### ISSUE TITLE
Installation and running ptable()

### ISSUE THREAD

**Issue by ppdewolf** [tenderle/ptable#1]
When I try to install, I get

> devtools::install_github("sdctools/ptable",build_vignette=FALSE) 
Downloading GitHub repo sdctools/ptable@master 
from URL https://api.github.com/repos/sdctools/ptable/zipball/master 
Installing ptable
"C:/PROGRA\~1/R/R-34\~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
   "C:/Users/Peter-Paul/AppData/Local/Temp/RtmpSQ0sTg/devtools24a84f2394/sdcTools-ptable-a2f38d8"  \   
   --library="E:/W7/Users/Peter-Paul/MyDocuments/R/win-library/3.4" --install-tests   
\* installing *source* package 'ptable' ... 
\*\* R 
\*\* inst 
\*\* preparing package for lazy loading 
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
    there is no package called 'flexdashboard' 
ERROR: lazy loading failed for package 'ptable' 
\* removing 'E:/W7/Users/Peter-Paul/MyDocuments/R/win-library/3.4/ptable' 
In R CMD INSTALL 
Installation failed: Command failed (1)

So apparently I need to install flexdashboard as well. So I install flexdashboard, then try again installing ptable from github. Now it does install 👍 

Then I load the package. Seems to work.

Then I try to run ptable(), I get

> ptable() 
Error in rmarkdown::run(file = "inst/pt_dashboard.Rmd") :
    The directory 'E:/W7/Users/Peter-Paul/MyDocuments/inst' does not exist 
In addition: Warning message: 
In normalizePath(path.expand(path), winslash, mustWork) :   
path[1]="inst": Het systeem kan het opgegeven bestand niet vinden

(Last part in Dutch is something like "Can't find the requested file")

**Comment by tenderle** [comment]
Thx, @ppdewolf 

The first issue regarding missing packages should be fixed.

**Comment by tenderle** [comment]
The second issue has to do with the path of the markdown file. I will have to find a solution sucht that `ptable()` will find the correct path.

**Comment by tenderle** [comment]
@ppdewolf Ok, I have implemented a workaround that should work for windows. I will fix it in two weeks.

**Comment by bernhard-da** [comment]
@tenderle i think i fixed this in #5 using `system.file()`

**Comment by tenderle** [comment]
@bernhard-da thx
