### ISSUE TITLE
Running fifi_plot()

### ISSUE THREAD

**Issue by ppdewolf** [tenderle/ptable#2]
I run the example
> ## basic example code
> params <- pt_create_pParams(D=3, V=0.7)
> ptable_destatis <- pt_create_pTable(params = params, type="destatis")

That seems to work 👍 

Then I try the next example
> ## plot the ptable
> fifi_plot(ptable_destatis)

I get
> Error in fifi_plot(ptable_destatis) : could not find function "fifi_plot".

Do I need another package?

**Comment by tenderle** [comment]
thx @ppdewolf 

The issue regarding `fifi_plot` is fixed.
