### ISSUE TITLE
combine pt_create_pParams() and pt_create_pTable()

### ISSUE THREAD

**Issue by bernhard-da** [tenderle/ptable#9]
this is a possible enhancement and simplification for users; i think it would be a good idea to merge this two functions and call `pt_create_pParams()` within `pt_create_pTable()`  and also only export `pt_create_pTable()` in the package namespace.

```
# pseudocode
pt_create_pTable <- function(D=5, V=3, js=2, label="test", type, ....) {
  pert_params <- pt_create_pParams(D=D, V=V, ...)
  ## continue
}

# user: no need to call pt_create_pParams()
pTable <- pt_create_pTable (type="abs", D=5, V=3)
```

**Comment by tenderle** [comment]
Thx, you made a good point. It may be more user friendly. That is how I handeled it with my very first version and it was a deliberate decision to outsorce the parameter function (at least while I will write the core funcionalities). However, I may undo this if the package is worthy to be published (after I added the ramaining funcionalities).

**Comment by tenderle** [comment]
Solved by the new functions `create_ptable()`, `create_cnt_ptable()` and  `create_cnt_ptable()`.
